name: flutter_viewer_usdz_example
description: Example app for flutter_viewer_usdz plugin
publish_to: 'none'

# Agregar versión explícita
version: 1.0.0+1  # <-- Esto es importante para iOS

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_viewer_usdz:
    path: ../
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true